### ISSUE TITLE
Style Issue: Two items in the "Town Size" selector dropdown are not capitalized

### ISSUE THREAD

**Issue by armelthelae** [bentomhall/GMPHelperWPF#11]
"Hamlet" and "Thorpe" in the dropdown for Town Size in the Settlement Generator are all lowercase where all other items have their first letter capitalized:

![image](https://user-images.githubusercontent.com/17966003/38462620-5071b39e-3ab8-11e8-8caf-40d2a5e23e2f.png)

**Comment by bentomhall** [comment]
Done.
